name: staging deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted
    steps: 
      - name: print hello world
        run: echo "hello world"

      - name: Install and Build ğŸ”§
        run: |
          mkdir -p dist
          cp -r src/* dist

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1 

      - name: Deploy code to Lucee server
        uses: muthukmr0909/github-workflow@staging
        with:
          BRANCH: main # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy to.
